### ISSUE TITLE
Validation runs

### ISSUE THREAD

**Issue by sharanbngr** [sharanbngr/blip#34]
Unless we are changing them we will use standard settings of fmin = 1e-4, fmax = 2e-2, duration = 2e6, seglen = 5e4, nside = 6, alpha=2/3, omega0 = 4.5e-9, seed=10, fs=0.25, FixSeed=1, mldc=0

**Orbiting vs Stationary: XYZ Channels**
- [x] with nside = 4 compare recoveries with stationary lisa and orbiting lisa setting. 
- [x] with nside = 8 compare recoveries with stationary lisa and orbiting lisa setting.  

optional run with nside =12

**Stationary LISA : XYZ channels**
- [x] Run with a series of Omega0 1e-12, 1e-11, 1e-10, 5e-10, 1e-9,  8e-9, 1e-8

**Stationary LISA : AET channels**
- [x] Run with a series of Omega0 1e-12, 1e-11, 1e-10, 5e-10, 1e-9,  8e-9, 1e-8

**Test nside effect**

- [ ] Using XYZ channels run with Omega0 = 1e-10, 1e-8 for nside of 6, 12 with stationary LISA

**Comment by kuan0020** [comment]
@sharanbngr 

This is my attempt for nside=4 for stationary lisa. let me know if something's wrong, if not I will do run it with other settings.

[params]
fmin=1e-4
fmax=2e-2
## duration in seconds, should be compatiable with fmin
duration=2e6
## segment length for fft in seconds, should be compatiable with fmin
## Note by SB: Looks like this needs to be atleast a factor of 10 larger than 1/fmin
## to give consistant recoveries.
seglen=5e4
## sample rate in Hz, should be compatible with fmax
## Note by SB: Looks like this needs to be atleast a factor of 4
## higher than fmax (as opposed to the usual factor of 2) to give
## consistent recoveries.
fs=0.25
Shfile=LISA_2017_PSD_M.npy
nside=4

## LISA configuration. Can be stationary or orbiting
lisa_config=stationary

## Level of the tdi. Can be michelson, xyz or aet
tdi_lev=aet

# If the mldc flag is set to 1, then the time series data is read in from a file.
mldc=0
datafile=SGWB_withnoise_full.txt

## Current options: SGWB_withnoise_full.txt mldc_tdi_withnoise.txt

## If loadResponse is true, then a previously generated set of detector responses is read in from a file. Only use when running repeated analyses on the same data set. Only used for orbiting LISA configuration due to the increased computation time of that case.
## File loaded depends on tdi_lev.
loadResponse=0

## If loadCustom is also true, the detector response arrays will be loaded from files specified by the user (responsefile1,2,3). Specified detector responses should be compatible with tdi_lev.
## IMPORTANT - only load responses when analyzing the dataset originally used to generate them. The code will throw an error if the duration/segment length (dur/seglen) don't match. However, mismatched combinations of data and responses can still function in some cases and will produce erroneous results.
loadCustom=0
responsefile1=R1arrayAETMLDC.txt
responsefile2=R2arrayAETMLDC.txt
responsefile3=R3arrayAETMLDC.txt

## fref parameter useful for powerlaw stochastic backgrounds
fref = 25
## recovery model type, can be isgwb, sph_sgwb, isgwb_only or noise_only for now
modeltype=isgwb
lmax=0
## Truevals for whatever parameters are being used.
## This should be a comma seperate list WITHOUT spaces
## For sph, the list is alpha, {log_omega_lm}, Np, Na
truevals=0.667,-8.455,-41.045,-48.443


[inj]
# Power Law Injection
# Omege0 is defined as the power at 1e-3 Hz
doInj=1
omega0=4.5e-9
alpha=0.667
Np=9e-42
Na=3.6e-49
injtype=isgwb

[run_params] # Parameters related to the run or to the sampler
out_dir=./stationary_n4_0
verbose=1
# Set doPreProc to 1 to force generation of fake data again rather than used
# precalculated data in the data_spectrum file
doPreProc=0
nlive=500
Nthreads=1
## If FixSeed is true, the sampler will use random states generated by the seed given in the 'seed' parameter below. This allows for reproduction of sampling results; for a given seed value, repeated analyses of the same dataset will produce precisely identical results. The seed can be any unsigned 32-bit integer.
FixSeed=1
seed=10
# Must be .npz file
input_spectrum=data_spectrum.npz

**Comment by sharanbngr** [comment]
Hi @kuan0020, in the params file change tdi_lev to xyz. Everything else looks okay. 

Regarding the error you emailed me about, I *think* that is because you don't have latex installed on your computer. Do

`sudo apt install texlive-full`

**Comment by kuan0020** [comment]
https://docs.google.com/presentation/d/1uuhY1vxJdz5bgdTFGf_aNqXFacbAgLIkde1D5BlHfA4/edit?usp=sharing
